# Generated by Django 4.2.1 on 2023-07-26 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livresse', '0004_book_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='img',
            new_name='img1',
        ),
        migrations.AddField(
            model_name='book',
            name='img2',
            field=models.ImageField(default=1, upload_to='uploads/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='img3',
            field=models.ImageField(default=1, upload_to='uploads/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='img4',
            field=models.ImageField(default=1, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
