# Generated by Django 4.2.1 on 2023-07-26 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livresse', '0005_rename_img_book_img1_book_img2_book_img3_book_img4'),
        ('livresse', '0007_category_catbook'),
    ]

    operations = [
    ]
