# Generated by Django 4.2.1 on 2023-07-26 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livresse', '0008_merge_20230726_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='img1',
        ),
        migrations.RemoveField(
            model_name='book',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='book',
            name='img3',
        ),
        migrations.RemoveField(
            model_name='book',
            name='img4',
        ),
    ]
