# Generated by Django 4.2.1 on 2023-07-27 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livresse', '0009_remove_book_img1_remove_book_img2_remove_book_img3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='img',
            field=models.ImageField(blank=True, default='', null=True, upload_to='uploads/'),
        ),
    ]
