# Generated by Django 4.2.1 on 2023-07-27 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livresse', '0010_book_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='img',
            new_name='img1',
        ),
        migrations.AddField(
            model_name='book',
            name='img2',
            field=models.ImageField(blank=True, default='', null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='book',
            name='img3',
            field=models.ImageField(blank=True, default='', null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='book',
            name='img4',
            field=models.ImageField(blank=True, default='', null=True, upload_to='uploads/'),
        ),
    ]
